services:
  db:
    image: mysql:8.0
    container_name: sports_store_db
    environment:
      MYSQL_DATABASE: sports_store
      MYSQL_USER: sportflow
      MYSQL_PASSWORD: sportflow123
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ../backend
    container_name: sports_store_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/sports_store?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: sportflow
      SPRING_DATASOURCE_PASSWORD: sportflow123
      JWT_SECRET: change-this-secret-in-production-change-this-secret
      JWT_EXPIRATION_MINUTES: 120
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ../frontend
    container_name: sports_store_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend

volumes:
  mysql_data:
