INSERT INTO categories (name, description) VALUES
('Natacao', 'Fatos de banho, oculos e equipamento de natacao'),
('Ciclismo', 'Capacetes, luvas e acessorios de ciclismo'),
('Fitness', 'Pesos, bandas elasticas e equipamento de ginasio');

INSERT INTO products (name, description, price, stock, active, category_id) VALUES
('Sapatilhas Trail Running', 'Sapatilhas para terreno irregular com sola agarre', 109.99, 30, TRUE, (SELECT id FROM categories WHERE name = 'Calcado')),
('Sapatilhas Basket', 'Sapatilhas de basquetebol com suporte tornozelo', 79.99, 25, TRUE, (SELECT id FROM categories WHERE name = 'Calcado')),
('Sapatilhas Padel', 'Calcado especifico para padel com sola espinha', 69.99, 35, TRUE, (SELECT id FROM categories WHERE name = 'Calcado')),
('Calcoes Desporto', 'Calcoes ligeiros com bolsos laterais', 18.99, 90, TRUE, (SELECT id FROM categories WHERE name = 'Vestuario')),
('Leggings Compressao', 'Leggings de compressao para corrida', 34.99, 60, TRUE, (SELECT id FROM categories WHERE name = 'Vestuario')),
('Casaco Corta-Vento', 'Casaco leve e impermeavel para desporto outdoor', 54.99, 40, TRUE, (SELECT id FROM categories WHERE name = 'Vestuario')),
('Meias Desportivas Pack 3', 'Pack de 3 pares de meias tecnicas antiderrapantes', 12.99, 120, TRUE, (SELECT id FROM categories WHERE name = 'Vestuario')),
('Bola de Basquetebol', 'Bola de basquetebol tamanho 7 grip premium', 29.99, 45, TRUE, (SELECT id FROM categories WHERE name = 'Equipamento')),
('Raquete de Padel', 'Raquete de padel carbono para nivel intermedio', 79.99, 20, TRUE, (SELECT id FROM categories WHERE name = 'Equipamento')),
('Raquete de Tenis', 'Raquete de tenis com cordas incluidas', 64.99, 22, TRUE, (SELECT id FROM categories WHERE name = 'Equipamento')),
('Bola de Rugby', 'Bola de rugby tamanho oficial com grip texturado', 24.99, 30, TRUE, (SELECT id FROM categories WHERE name = 'Equipamento')),
('Mochila Desporto 30L', 'Mochila resistente com compartimento calcado', 44.99, 50, TRUE, (SELECT id FROM categories WHERE name = 'Acessorios')),
('Garrafa Termica 750ml', 'Garrafa de aco inoxidavel com isolamento duplo', 22.99, 70, TRUE, (SELECT id FROM categories WHERE name = 'Acessorios')),
('Cinto de Hidratacao', 'Cinto com 2 garrafas para corrida de longa distancia', 29.99, 25, TRUE, (SELECT id FROM categories WHERE name = 'Acessorios')),
('Pulseira GPS Desportiva', 'Monitor de atividade com GPS e cardiofrequencimetro', 149.99, 15, TRUE, (SELECT id FROM categories WHERE name = 'Acessorios')),
('Fato de Banho Competicao', 'Fato de banho de competicao hidrodinamico', 49.99, 20, TRUE, (SELECT id FROM categories WHERE name = 'Natacao')),
('Oculos Natacao', 'Oculos anti-niebla com protecao UV', 17.99, 55, TRUE, (SELECT id FROM categories WHERE name = 'Natacao')),
('Touca de Silicone', 'Touca de natacao em silicone premium', 8.99, 80, TRUE, (SELECT id FROM categories WHERE name = 'Natacao')),
('Capacete Ciclismo', 'Capacete leve com ventilacao otimizada', 59.99, 18, TRUE, (SELECT id FROM categories WHERE name = 'Ciclismo')),
('Luvas Ciclismo', 'Luvas com palma acolchoada para longas distancias', 19.99, 45, TRUE, (SELECT id FROM categories WHERE name = 'Ciclismo')),
('Halteres 5kg Par', 'Par de halteres revestidos a borracha 5kg', 34.99, 30, TRUE, (SELECT id FROM categories WHERE name = 'Fitness')),
('Banda Elastica Resistencia', 'Set de 3 bandas elasticas de resistencia variavel', 14.99, 65, TRUE, (SELECT id FROM categories WHERE name = 'Fitness')),
('Tapete Yoga', 'Tapete de yoga antiderrapante 6mm espessura', 27.99, 40, TRUE, (SELECT id FROM categories WHERE name = 'Fitness')),
('Produto Descontinuado', 'Produto inativo para demonstracao de gestao de disponibilidade', 9.99, 0, FALSE, (SELECT id FROM categories WHERE name = 'Acessorios'));
