spring:
  datasource:
    url: jdbc:h2:mem:shopping_food_store_demo;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

app:
  security:
    jwt-secret: demo-secret-key-demo-secret-key-demo-secret-key
    jwt-expiration-minutes: 120

logging:
  level:
    root: info
    pt.ubi.gruposd.loja: info
